### ISSUE TITLE
keycloakify 7.3.1 starter project issues

### ISSUE THREAD

**Issue by mkreuzmayr** [keycloakify/keycloakify#285]
I am getting these errors when updating keycloakify to 7.3.1 in the starter project. Any ideas?

```
TypeError: args[i].replace is not a function
    at populateTemplate (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\trimIndent.js:49:33)
    at trimIndentPrivate (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\trimIndent.js:61:35)
    at trimIndent (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\trimIndent.js:84:30)
    at D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\jar.js:71:68
    at step (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\jar.js:37:23)
    at Object.next (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\jar.js:18:53)
    at D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\jar.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\jar.js:8:12)
    at jar (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\tools\jar.js:60:12)
    at D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\keycloakify.js:133:60
    at step (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\keycloakify.js:56:23)
    at Object.next (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\keycloakify.js:37:53)
    at fulfilled (D:\Temp\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\keycloakify.js:28:58)
```

**Comment by willwill96** [comment]
I think this line may be iterating over the incorrect array:
https://github.com/keycloakify/keycloakify/blob/main/src/bin/tools/trimIndent.ts#L7
